image:
  file: Dockerfile
ports:
- port: 8050
  onOpen: open-preview
- port: 8888
  onOpen: open-browser
tasks:
- command: pyenv global 3.7.4 &&
           chmod +x envconfig.sh
           ln -s /opt/conda/bin  /workspace/my-gitpod-of-spleeter/opt-conda-bin
           ln -s /workspace/conda/arcw/bin  /workspace/my-gitpod-of-spleeter/conda-arcw-bin
           

            
   
